<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup><UserSecretsId>minha-escala-saas-local</UserSecretsId></PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../Infrastructure/Infrastructure.csproj" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="10.0.12" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.12" PrivateAssets="all" />
  </ItemGroup>
</Project>
